spring.application.name=jodel
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
logging.level.root=info

server.port=8082

spring.datasource.url=jdbc:postgresql://spring-db:5432/jodel
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.data-locations=classpath:data.sql

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8180/realms/jodel
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:8180/realms/jodel/protocol/openid-connect/certs

